### ISSUE TITLE
tuple concat doesn't work with field kinds of nnkBracketExpr or nnkTupleConstr possibly others

### ISSUE THREAD

**Issue by mahmadzaid** [rotu/nim-records#3]
I'm not sure if this package is still maintained (?); below is a MWE of the issue:
```nim
import records
discard (1, '2', "3") & ([1,2],3)
# /home/<user>/.nimble/pkgs/records-0.5.2/records/tupleops.nim(26, 18) Error: Unexpected field kind: `nnkBracketExpr`
```
and with:
```nim
discard (1, '2', "3") & ((1,2),3)
# /home/<user>/.nimble/pkgs/records-0.5.2/records/tupleops.nim(26, 18) Error: Unexpected field kind: `nnkTupleConstr`
```

**Comment by rotu** [comment]
Thank you! I'm not actively maintaining this package - I mostly did it because I thought it was cool that it's possible in Nim!

Please let me know if the fix works for you and I'd love to know what you're using this project for

**Comment by mahmadzaid** [comment]
Yes, the last commit works, I'm revisiting Nim again (since 0.19) and as a way to learn, I'm porting a python [package](https://github.com/CourtBouillon/pydyf), so I have a few expectations common with people coming from python, there are probably better ways to do things in Nim.

Thank you, really appreciate taking the time to fix this!
